### PR TITLE
Add missing requirement

### PR DESCRIPTION
**Pull request by ctjhoa**
`wasm-pack` is mandatory to build this project.
I took the latest version of wasm-pack, not sure which is the minimum version required.

### CODE REVIEW

**Comment by MartinKavik** [comment]
It should install automatically when needed by `cargo-make`. So I assume there is a bug - could you investigate it a little bit more on your machine?

**Comment by ctjhoa** [comment]
I had an old version of `wasm-pack` so I guess `cargo-make` isn't able to upgrade it. However I will do more tests on my laptop.

**Comment by MartinKavik** [comment]
Ok, I'll merge it, it's a good reason. `cargo-make` should also install automatically wasm target, but it's not 100% on some platforms. So it's a more work for user but we have better chance that he will be able to build the project.

If you find better solution, create another issue / PR, please.

Thank you!

**Comment by ctjhoa** [comment]
@MartinKavik FYI, I confirm my assumption. This project requires `wasm-pack 0.8.0`  at least. If you try with `wasm-pack 0.7.0` you get this:

```
🧐  Checking for wasm-pack...

✅  wasm-pack is installed.

ℹ  Compiling your crate in development mode...

error: Found argument '--out-name' which wasn't expected, or isn't valid in this context
        Did you mean --out-dir?

USAGE:
    wasm-pack build --out-dir <out_dir>

For more information try --help

✔ Webpack
  Compiled successfully in 3.78s


✖ Webpack
  Compiled with some errors in 550.72ms

✖ ｢wdm｣:
ERROR in Rust compilation.
```

**Comment by MartinKavik** [comment]
Thanks, it looks like this issue: https://github.com/David-OConnor/seed-quickstart/pull/13

**Pull request merged**
